export const graphDataInit = {
  graph: null,
  originGraph: null,
  linkWeightMin: null,
  linkWeightMax: null,
  mergeProteins: false,
  nodeMap: null,
  circles: null,
  nodeLabels: null,
  lines: null,
  filteredAfterStart: false,
  graphIsPreprocessed: false,
  activeGraphFileNames: null,
  uploadedGraphFileNames: null,
  activeMapping: null,
  uploadedMappingNames: null,
};
