import {
  borderHeightInit,
  borderWidthInit,
  checkBorderInit,
  circleLayoutInit,
  communityForceStrengthInit,
  compDensityInit,
  componentStrengthInit,
  linkFilterInit,
  linkFilterTextInit,
  linkForceInit,
  linkLengthInit,
  linkThresholdInit,
  maxCompSizeInit,
  minCompSizeInit,
  minNeighborhoodSizeInit,
  nodeFilterInit,
  nodeFilterTextInit,
  nodeRepulsionStrengthInit,
  xStrengthInit,
  yStrengthInit,
} from "../GraphStuff/graphInitValues.js";

export const resetPhysicsSettings = (setSettings) => {
  setSettings("physics", {
    circleLayout: circleLayoutInit,
    xStrength: xStrengthInit,
    yStrength: yStrengthInit,
    componentStrength: componentStrengthInit,
    componentStrengthText: componentStrengthInit,
    nodeRepulsionStrength: nodeRepulsionStrengthInit,
    linkForce: linkForceInit,
    linkLength: linkLengthInit,
    checkBorder: checkBorderInit,
    borderWidth: borderWidthInit,
    borderHeight: borderHeightInit,
    linkLengthText: linkLengthInit,
    borderHeightText: borderHeightInit,
    borderWidthText: borderWidthInit,
    xStrengthText: xStrengthInit,
    yStrengthText: yStrengthInit,
    nodeRepulsionStrengthText: nodeRepulsionStrengthInit,
    communityForceStrength: communityForceStrengthInit,
    communityForceStrengthText: communityForceStrengthInit,
  });
};

export const resetFilterSettings = (setFilter, currentFilter) => {
  setFilter({
    ...currentFilter,
    linkThreshold: linkThresholdInit,
    linkFilter: linkFilterInit,
    linkFilterText: linkFilterTextInit,
    nodeFilter: nodeFilterInit,
    nodeFilterText: nodeFilterTextInit,
    minCompSize: minCompSizeInit,
    minCompSizeText: minCompSizeInit,
    maxCompSize: maxCompSizeInit,
    maxCompSizeText: maxCompSizeInit,
    linkThresholdText: linkThresholdInit,
    compDensity: compDensityInit,
    compDensityText: compDensityInit,
    minNeighborhoodSize: minNeighborhoodSizeInit,
    minNeighborhoodSizeText: minNeighborhoodSizeInit,
  });
};
